---
kind: ProjectRequest
apiVersion: v1
metadata:
  name: robot-shop

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cart
  labels:
    service: cart
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      service: cart
  template:
    metadata:
      labels:
        service: cart
    spec:
      containers:
      - name: cart
        image: robotshop/rs-cart:latest
        # agent networking access 
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi

---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: robot-shop
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: cart

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: catalogue
  labels:
    service: catalogue
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      service: catalogue
  template:
    metadata:
      labels:
        service: catalogue
    spec:
      containers:
      - name: catalogue
        image: robotshop/rs-catalogue:latest
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: catalogue
  name: catalogue
  namespace: robot-shop
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: catalogue

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dispatch
  labels:
    service: dispatch
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      service: dispatch
  template:
    metadata:
      labels:
        service: dispatch
    spec:
      containers:
      - name: dispatch
        image: robotshop/rs-dispatch:latest
        env:
          # agent networking access
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: dispatch
  labels:
    service: dispatch
  namespace: robot-shop
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: dispatch

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    service: mongodb
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb
  template:
    metadata:
      labels:
        service: mongodb
    spec:
      containers:
      - name: mongodb
        image: robotshop/rs-mongodb:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: "/data/db"
          name: mongodb-volume
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
      volumes:
      - name: mongodb-volume
        persistentVolumeClaim:
          claimName: mongodb-volume-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-volume-claim
  namespace: robot-shop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: mongodb
  name: mongodb
  namespace: robot-shop
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    service: mongodb

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    service: mysql
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        service: mysql
        name: mysql
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      initContainers:
      - name: post-hook
        command:
        - /bin/sh
        - -c
        - cp -r /tmp/post-scripts/* /var/lib/mysql/ && mkdir /var/lib/mysql/data
        imagePullPolicy: Always
        image: docker.io/pranavgaikwad/robot-shop-mysql-post-hook:latest
        volumeMounts:
        - mountPath: "/var/lib/mysql/"
          name: mysql-data-volume
      containers:
      - name: dataloader
        image: registry.redhat.io/rhscl/mysql-57-rhel7:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/var/lib/mysql/"
          name: mysql-data-volume
        command:
        - /bin/sh
        - -c
        - sleep 120 && zcat /var/lib/mysql/10-dump.sql.gz | /opt/rh/rh-mysql57/root/bin/mysql --force -h $MYSQL_SERVICE_HOST -u root -pR00t@123 -D $MYSQL_DATABASE -P 3306 && /opt/rh/rh-mysql57/root/bin/mysql -h $MYSQL_SERVICE_HOST -u root -pR00t@123 -P 3306 < /var/lib/mysql/20-ratings.sql && sleep infinity
        env:
        - name: MYSQL_USER
          value: shipping
        - name: MYSQL_PASSWORD
          value: secret
        - name: MYSQL_DATABASE
          value: cities
      - name: mysql
        imagePullPolicy: Always
        image: registry.redhat.io/rhscl/mysql-57-rhel7:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_USER
          value: shipping
        - name: MYSQL_PASSWORD
          value: secret
        - name: MYSQL_DATABASE
          value: cities
        - name: MYSQL_ROOT_PASSWORD
          value: R00t@123
        resources:
          limits:
            cpu: 200m
            memory: 800Mi
          requests:
            cpu: 100m
            memory: 400Mi
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-data-volume
      restartPolicy: Always
      volumes:
      - name: mysql-data-volume
        persistentVolumeClaim:
          claimName: mysql-data-volume-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-volume-claim
  namespace: robot-shop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: mysql
  name: mysql
  namespace: robot-shop
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    service: mysql

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: payment
  labels:
    service: payment
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      service: payment
  template:
    metadata:
      labels:
        service: payment
    spec:
      containers:
      - name: payment
        image: docker.io/pranavgaikwad/robot-shop-payment:latest
        # agent networking access
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    service: payment
  namespace: robot-shop
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: payment

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    service: rabbitmq
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rabbitmq
  template:
    metadata:
      labels:
        service: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7-management-alpine
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    service: rabbitmq
  namespace: robot-shop
spec:
  ports:
  - name: tcp-amqp
    port: 5672
    targetPort: 5672
  - name: http-management
    port: 15672
    targetPort: 15672
  - name: tcp-epmd
    port: 4369
    targetPort: 4369
  selector:
    service: rabbitmq

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ratings
  labels:
    service: ratings
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ratings
  template:
    metadata:
      labels:
        service: ratings
    spec:
      containers:
      - name: ratings
        image: docker.io/pranavgaikwad/robot-shop-ratings:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    service: ratings
  namespace: robot-shop
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: ratings

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    service: redis
  name: redis
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
      - name: redis
        image: redis:4.0.6
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
        - mountPath: "/data"
          name: redis-volume
      restartPolicy: Always
      volumes:
      - name: redis-volume
        persistentVolumeClaim:
          claimName: redis-volume-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: robot-shop
  name: redis-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: redis
  name: redis
  namespace: robot-shop
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    service: redis

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shipping
  labels:
    service: shipping
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      service: shipping
  template:
    metadata:
      labels:
        service: shipping
    spec:
      containers:
      - name: shipping
        image: robotshop/rs-shipping:latest
        ports:
        - containerPort: 8080
        # it's Java it needs lots of memory
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 500Mi
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    service: shipping
  namespace: robot-shop
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: shipping

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user
  labels:
    service: user
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      service: user
  template:
    metadata:
      labels:
        service: user
    spec:
      containers:
      - name: user
        image: robotshop/rs-user:latest
        env:
          # agent networking access
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    service: user
  namespace: robot-shop
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: user

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
    service: web
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
      - name: web
        image: docker.io/pranavgaikwad/robot-shop-nginx:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        # securityContext:
        #   privileged: true
      restartPolicy: Always

---
apiVersion: v1
kind: Route
metadata:
  name: front-end
  namespace: robot-shop
spec:
  path: "/"
  port:
    targetPort: http
  to:
    kind: Service
    name: web



---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    service: web
  namespace: robot-shop
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: web

