---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ssh-server
  namespace: test-ssh
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - privileged
