---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssh-server-claim
  namespace: test-ssh
  labels:
    ssh-server: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
