---
apiVersion: v1
kind: Service
metadata:
  name: ssh-service
  namespace: test-ssh
spec:
  selector:
    ssh-server: "true"
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 22
      targetPort: 22
